name: pin_app_challenge
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  either_dart: ^1.0.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.5
  pin_app_challenge_post_sdk:
    path: ../pin_app_challenge_post_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
